CREATE TABLE Customer (
	Account_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	F_name VARCHAR(255) NOT NULL,
    L_name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
	Password VARCHAR(255) NOT NULL,
    Birthdate DATE NOT NULL,
    Address VARCHAR(255) NOT NULL,
    Username VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Products (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price VARCHAR(255) NOT NULL
);

-- ALTER TABLE Users ADD UNIQUE (username);
