
DROP TABLE IF EXISTS Works_At;
CREATE TABLE Works_At
(
    E_ID TINYINT(4) UNSIGNED NOT NULL REFERENCES Employee(E_ID),           
    W_ID TINYINT(4) NOT NULL REFERENCES Warehouse(W_ID)
);
        
INSERT INTO Works_At (E_ID, W_ID) VALUES (1, 1);
INSERT INTO Works_At (E_ID, W_ID) VALUES (2, 2);
INSERT INTO Works_At (E_ID, W_ID) VALUES (3, 3);
INSERT INTO Works_At (E_ID, W_ID) VALUES (4, 4);
INSERT INTO Works_At (E_ID, W_ID) VALUES (5, 5);
INSERT INTO Works_At (E_ID, W_ID) VALUES (6, 6);
INSERT INTO Works_At (E_ID, W_ID) VALUES (7, 7);
INSERT INTO Works_At (E_ID, W_ID) VALUES (8, 8);
INSERT INTO Works_At (E_ID, W_ID) VALUES (9, 9);
INSERT INTO Works_At (E_ID, W_ID) VALUES (10, 10);
INSERT INTO Works_At (E_ID, W_ID) VALUES (11, 11);
INSERT INTO Works_At (E_ID, W_ID) VALUES (12, 12);
INSERT INTO Works_At (E_ID, W_ID) VALUES (13, 13);
INSERT INTO Works_At (E_ID, W_ID) VALUES (14, 14);
INSERT INTO Works_At (E_ID, W_ID) VALUES (15, 15);
INSERT INTO Works_At (E_ID, W_ID) VALUES (16, 16);
INSERT INTO Works_At (E_ID, W_ID) VALUES (17, 17);
INSERT INTO Works_At (E_ID, W_ID) VALUES (18, 18);
INSERT INTO Works_At (E_ID, W_ID) VALUES (19, 19);
INSERT INTO Works_At (E_ID, W_ID) VALUES (20, 20);
