
DROP TABLE IF EXISTS Works_At;
CREATE TABLE Works_At
(
    E_ID TINYINT(4) UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    F_name VARCHAR(255) NOT NULL,
    L_name VARCHAR(255) NOT NULL,
    Birthdate DATE NOT NULL,
    SSN VARCHAR(9) NOT NULL UNIQUE,
    W_ID TINYINT(4) NOT NULL REFERENCES Warehouse(W_ID),  
    Hire_Date DATE NOT NULL
);
        
